### PR TITLE
New King-Meter library

### PR DESCRIPTION
**Pull request by MichaelFabry**
Introducing support for King-Meter KM5s/901U and KM5s/618U (EBS-LCD2) displays. Re-wrote entire code for J-LCD, SW-LCD and compatibles. New API common for all King-Meter displays.

### CODE REVIEW

**Comment by thomasjfox** [comment]
This code is completely merged. Closing pull request.

**Comment by JenusL** [comment]
This is probably not the right place to post this but I don't know how else to contact you...
@MichaelFabry Do you have the specification of the KM5s/618U protocol at hand and are willing to share it?

**Comment by MichaelFabry** [comment]
Hi JenusL,
the specs are property of Kingmeter, so I can't share them.
However, you can ask Kingmeter directly- this is how I got them.
If you send me an email to michael@fabry.de, I will forward you the email-address of my contact at Kingmeter.

**Comment by JenusL** [comment]
No problem. I actually just got the full protocol figured out by looking at the source code of an android app. That will do for now.
But if I end up needing it in the future it's good to have your address.
Thanks!

**Pull request closed without merging**
